language: ruby
rvm:
- 2.5.1
cache: bundler
install: bundle install
script: jekyll build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: BbjY+YARTEAxFRxHA+ax6btTfUlimG+vPZdI97sgeDZIdEhu0fxXCuKFDrClNLr3yzUyVpeuawtmpJMhwULIcA99kHDb8rK79On7ZhvmX+rrjtTTyM596/tcLOw7S1RaMYJUP1h/pOiqZT2Fkza66gHrwH8pQgRWvqWnHRJ7ccrGXiufkET372NueGe51krQ26RFFDPoGkMqNBRnhTW7yvFye3Wws7S5f2pMgPTlCbbCXImUHHIxYCTnlusnHZwyIOVLlVPStX6blz8Dz1ia/s49G6/ZMtO/wK5mE3gEm3X0jRse07DpT63GGFd8Aq8rnwQMGQv/OseZKNoh0aowYTLUemBLBdPVgxhC6SjM8AlW7dmoSd/F1QI6wrF5Bdj5bzmyNYQGXQutZ3pBVQdMnrZsiFFYTnS9lqvbeOwxmk80X/86hD/P/gmyYtWaNA0rhmEWuoZ4+abMx++ynvb7koZqjWChABcibq54UB87H+gM8gcAW1xla27ylOTHjjQVYwznUlC3xgk97HnfC1Uw/CACwRrwc+DYNfnqgXDkRgCI082+VCCf69YnpPeOQIb18Sdg0eSGFznvsPCLcOBHpldXLOn8TPYHa4cxkIUM7Bp47Ib3Td3uGfbisOFySbiPbo5V8I+6ccV6kcHZn4Ef0Bw8e0EqMzGe4AZPP7mfqnE=
  on:
    branch: master
env:
 - JEKYLL_ENV=production
