language: ruby
rvm:
- 2.7
cache:
  bundler: true
  directories:
  - ".firebase"
  - ".jekyll-cache"
  - vendor/bundle
before_install: gem install bundler
install: bundle install
script: jekyll build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: ahOA5fawgi5jcJyQ0hy9enemv3YPSDre3Mq6voAOQyvDDgZZHr3IHxd6bePMHZx1qo3gPppVx4RHRpba3JfjB4zULV5z1U+MnJ6AlwI8m9ZFXwjKjchM1iZOy3WTFzehF935gFH6gTAx4erukNKiJcaHU1uS5AObm0yLv5tyDzcZM71Iv3/pmyQM/YJ1RTFmNH4HfLzSIBnrDPPZesXCJmNRVeDpf9j7gUCw583Te95xzCiDJN37eNXTmRqlXSPi/LTV57MsVj5pdJLpw5CENRX85KaIG5uXZ4ia/61h0iZzav0xJBj2IIOaqKZOUOcZEElOIdR6qaZM5ICpiCZmE7Ik4yB4aJsfmcf8fmuEclgspHLFbOHx4gNAxZlHgh9P60ZdcUzNDlvzuRp6XXGhf8bwAx0CVuwkFk+MlOgtOgOq3lBJcgYxraNmq3MAJBRpRezGlNsdnW+J1ZcSObfJ57q7vRoXixvBSI38Gy+JssDO2+JzHe63F9Iz+Dmiv1y4jQZm6qLJ0CxnmoZyIOXo0Nwimi/ei80WWSLm8c1KiN3zib1jvGzVrmKt/X9VhEtyuXcbCDFBI6cLcSHzzMYXG6DIXtmW5Y2Yh7+6OD0vdlrb4XtSQaYWWbpjUciz9KVRFX29AoHxBbyr/vE/7H6KqKT0idfo1joa4v73oUnbV6M=
  on:
    branch: master
env:
  matrix:
  - JEKYLL_ENV=production