language: ruby
rvm:
- 2.5.1
cache: bundler
install: bundle install
script: jekyll build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: StwTbFHYGuWfKwjMHHBCJz42LDM6agpC2BpfmD4Jbmy3Bjmieb6p5PzILfGwvP9TMqwWOBGQYVU/c43Hl7/eyDAL7N23HagR9O2uHevsmrHRYnn4UFjSMreYk+9qj6PqI8ZkZz9biVUQ5t5IW6UdYOfeEv/NJZbv7wn1USwTzVo+U7Nx0gX/v7tYDgPhTIHI9U68MlLW2iZlgHkTuN/gqebnifr+wAFxey47h1CdMfdMXtOB309fxFHsKVlpSCKcp//lOj/j9YTNCqbJvAX4dIoO+IivFfteiIOHE4OmuNyk0yJTR/YFmonEBJq2Tr8ob5DrgZb+RUBZFlCc6co0Rme/sP/AHX+lpcDdfEsEAjQycws236NX9EV/PvEkci0MVGf9ecdIYSLhx+LCTUn3hYsqzhhtpAQt3V/wz93Mh7xSy8iZX1Z/isohen89naMytkxnK0nZ//XtU7S8lxxXRVZCQMaZV+4Re0xoKxbf59NocL54pOCwtDy1V4JP6cRDjws8ltOToO/ia4yYRIxTkUQdsQNhDIKiYtYUsBqn3SJxYT1b5fak3dJ4G0I96OmoocIV9VoHdbM02RmUaJNMwVamTnE/cvho8RsXoproiP2nOzGk8VYAt1umtUV97IjEEWzY0MRVs7cImtITe9KAkal7gc70PTZdCo7qVD0l6ac=
  on:
    branch: master
env:
 - JEKYLL_ENV=production
