language: ruby
rvm:
- 2.5.1
cache: bundler
install: bundle install
script: jekyll build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: f5t6wvN0/iceOardDEsF4czKHBTdmMuVl6cDdo7jfYHpyWPcL5EybcETflzY0u/cbS04F+bi7YNZPYBOh9WOImq3IqZxZU/AF3MQ2jNnBcapBoV+QrMReM0NaI1jJY1/NP1zSLs/sJJVZIvkXoZyoVcrNoyKedr6ZACNQD2C8H6uk1D04lH25DcrUG4dEtT6xB2WSZ3An4g/3mpVQeRi91dlx4zbyQKL8QE7Tho5FK8D4S2TWvDG+VtjMJe+xByvSIGdvQCxYvhV/14gds7BKHOVapIUQ0O9W6ckc/T3hdRDqzopnATtF1uwemyxAvRiZWg7qqb+6Wvf6xcZdd2fmKKfYjO7SgYAYP4/hTvbK7J3HiXVlmWQbe3/u4qi3dBG8joi2yvPfvcHkFCCaf/Jm+e/uj+DeWEQI0TT6EVyVrpHOGZz6YblnoO0LBMiNaWNqobjaG+FndYmHU9UhGbm8JvO62uNL1f37Ggupb/7wpRzccCizEoFHhEZaGY84q/GPe0nWvxHOGu2kbzowW7N2JZB7DeV+ZTKqM/Mn/1J9pRVnfIR3oV9YnKpxTL0LNSN3+L9BToCYr0b4b4FiH+rom0oaJn0Ty1rwqFxlUbfSIWPckP6WzDBCGr1Ar9FH2enRQ7CuOV4oJ12l33MLIOnGjNhdfRC5tGN74CaUu6t4SE=
  on:
    branch: master
env:
 - JEKYLL_ENV=production