language: ruby
rvm:
- 2.7
cache:
  bundler: true
  directories:
  - ".firebase"
  - ".jekyll-cache"
  - vendor/bundle
before_install: gem install bundler
install: bundle install
script: jekyll build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: QMd8ufXo2yrdjJ5zmX/pRd9fPW7sty5PqQngPhpGMiwv+cchVQvEYjkWS9bKVk25VNqPNh1yClC01qAszuY0pmiHqiQIN9QyqhZCwOrIt4xImK0zRobCu3mwWsY/FmQmUGmzoNXxADBfKUZuYjAOJ6AJHk8ISZwXq4hSsXYeo193jXvU6ETj53fY7xWDg0LGVfbNZ59+axIx/nrIPvrvZa7L800D5blqKnE4IrhQmE2R/Z6nlTlNVin0O9Bu/2LlpelXaWVi38jhtVOY3YGBj/3EN9DFUdEz07ZDr/E7tsh2iXe85YFpQFnOrq97D6QPnPtzHaL8wxM5G69guz+xs0XjyL3Fhci/W7e9A3yPYd8vFjpcaxxB1AGhIYaD1PyDYVD1lv9IqYX9FOZAutTwk+38qFaJoBSaMK/WsSCgcw64j3L2yVGWFYAPg2w7ksz8naZKudSn8NiWbIrCZTy1A8xWyDz3iiZK+giB0A8wVI9AIo4Yae1rYt8avBkaKyXeaXbYPrGLFUOOvBRioCuVerwgj+5XoQ9PUbSB6Sqrt7AftfBi/o481toQkzoG23i/ELvDVVcuVOSbNJfobDylwq5TRNrndq+L5JMZUreDPQWF12jEiwmNQELc+kNajbZ5PcbrqwqlB69k/EH61o3Ebfg1/bH/Xc5F4jDOOUbVvgI=
  on:
    branch: master
env:
  matrix:
  - JEKYLL_ENV=production
  global:
    secure: MSNqvVFfr5paDuMmWn064gwSg2GM+hMKn84SWApqY1IksqahQHrP5zgOWPmK4S7GIsHpL1XYYfhJghCt9bxCW7d8UBrUS1lgviuIQWGcsY31saNTHBLca3B/56EENpvGM98xuYrVeeC++eIFUlzGy4aWs1i5qPLuocd/3/t9Unamo+4lZrmjTwXJBAZqEQ1HA4I/QwuCUteBTpc4tyWy6XyOtC0ahpfss6NHjUflXzBTRP2GZ9VsrRQEPKcUXI9cO9H9vuGIH2bHlOtf1+B36s5VfwxDU3eplYnAZVeVtesrzPJgHgjGQ4cwgFfXXt0Tee8JxZqEiqd29PUUrqbz3KNpZlUDJAqdfTfmVpcIM9J5FjszUBfQgyAm3l1VKL6+PnSqyE3JeeKPywD2ZkI27SZwTul56M36Jr2WxP0N9sLtDrrNL/vvtyY+Pl/pk92hurVNFtqqjLdCsgdv8y6si6YBh4zaqsq8dCIi+SvboxKpFxOc85oy12jBH1NysAxDIokoaIywGTW7TKGtLK4sRBlADWt3efukjGUOAxhwb32gYBeCCrj81kydoSMVoJkMHhLC86Kur+noPo+0b4rVpoDP3RtGOxU2YYykhir58+za05DPtn86Pzgng6JXH3VoJM6RRhzcxoy7UgHHtlzC6U98qVG43KgayKLNSOebX+w=
