language: ruby
rvm:
  - 2.5.1

cache: bundler

install: bundle install
script: jekyll build

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "Yf80+Nol54DzI8w7hZIPISBWEw616uFGz8HeDnYKDVDVHnfYj5V9OXi2aCNANPmr7+knxpx005NFPbyqnNaqdAryEDPn3V0Lb+37foSuach9XhOQu5ogWGRNT+DEsAVkPZLeAbllkfOFQwUGF5iZRUgv1+GV/HV3sEVCbHfPidGxSFIz8+nKxP14XXEc2eF9pvAlcGvpLY7L00s2OYdDtMHGPr1kp1MOnzuHWYLPMD0ls/baCzUpyCoTBDm7hoP1gkY41I2vJbMKXDBUjFPtM8t0EY5WZxOKq+V3LV8wRd80kBGdZLkgjznl8o2tjd+WoPh9Xah4X58eQaJJ/tgfbB41e0r2JncwWPTaGe94OXGiYn2jxJros8fdg/hC2oSUQkSI38wK3Kfh/1LHMYInxVnqKC/ZRFDCK3XG9c7eWUEU5CkekHWn5P083/E/RogOD28Z6Jn/a3cgzo6z9EIoT+7QQGt09tZyGiUwepBdUgcRhAWThPjkd/pNoBcsqfy1Daevgx3JXBlMjhKMKu6Gb+jQQHEnVHvNZVl+rVTdckCKxUYlaSnpR/v6oDM+fKf3LplMJBU8S9++BMwFqu4faUxCTqNcVi/6EYh/SoRB8plRMleobjo61jWfa1nPEGhWi66pCUUB4mHIYh4KTwrKTRFU8AiEQ7fz4XkgyYkUvW4="
  on:
    branch: master

env:
 - JEKYLL_ENV=production